Clean up the output of the box tests if the test fails.

diff --git a/tests/box/common.sh.in b/tests/box/common.sh.in
--- a/tests/box/common.sh.in
+++ b/tests/box/common.sh.in
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -e
+
 NP=$1
 ltqt=$2
 test=$3
@@ -27,6 +29,13 @@ outdir=@abs_builddir@/$test/out
 # The reference output is checked into the source direcory.
 refout=@abs_top_srcdir@/verification_tests/output/$out
 
+# cleanup on failure.
+function cleanup {
+    echo "Removing $out $outdir"
+    rm -rf $outdir $out
+}
+trap cleanup EXIT
+
 # Run the PGFem3D test
 cmd="mpirun -np $NP $pgfem $@ $indir/box_${ltqt}_${NP}CPU/box_${ltqt}_ ${outdir}/box_${ltqt}"
 echo $cmd
@@ -39,3 +48,4 @@ $cmd
 
 # And check the results.
 numdiff --absolute-tolerance=1.0e-14 --relative-tolerance=1.0e-14 $out $refout
+cleanup
diff --git a/tests/box/compression/run.sh.in b/tests/box/compression/run.sh.in
--- a/tests/box/compression/run.sh.in
+++ b/tests/box/compression/run.sh.in
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # The pgfem executable is built in the build directory.
 pgfem=@top_builddir@/src/PGFem3D
@@ -23,6 +24,13 @@ refout=@top_srcdir@/verification_tests/output/plasticity_order_of_error.txt
 # The options that we use to run the applications.
 opts="-SS -cm 1 -V "
 
+# cleanup on failure.
+function cleanup {
+    echo "Removing $out $outdir"
+    rm -rf $outdir $out
+}
+trap cleanup EXIT
+
 # Run the PGFem3D test
 cmd="$pgfem $opts $indir/box_LT_ $outdir/box_LT"
 echo $cmd
@@ -35,3 +43,4 @@ $cmd
 
 # And check the results.
 numdiff --absolute-tolerance=1.0e-14 --relative-tolerance=1.0e-14 $out $refout
+cleanup
